type ProfileType = {
  // _id: string;
  // name: string;
  // image: string;
  // raiting: number;
  // description: string;
  _id: string;
  name: string;
  email: string;
  phone: string;
  password: string;
  address?: string;
  about?: string;
  gender?: boolean;
  image?: string;
  passport_id?: string;
  review?: string[];
  otp?: string;
  info_id: string;
};
